language: d
d:
  - dmd
  - gdc
  - ldc
install:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.1.6/doveralls_linux_travis"
  - chmod +x doveralls
script:
  - dub test -b unittest-cov --compiler=${DC}
  - ./doveralls
